#!/usr/bin/env ruby
require "Yaak0v_palindrome"
require "open-uri"

lines = URI.open('https://cdn.learnenough.com/phrases.txt').readlines
lines.each do |line|
    if line.palindrome?
        puts "palindrome detected #{line}"
    end
end

